### ISSUE TITLE
Adjust size of  in-memory block cache

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#47]
bifrost-gateway runs with in-memory [2Q cache](https://pkg.go.dev/github.com/hashicorp/golang-lru/v2#TwoQueueCache) with size set to  1024 blocks.

> 2Q is an enhancement over the standard LRU cache in that it tracks both frequently and recently used entries separately. This avoids a burst in access to new entries from evicting frequently used entries.

## Current cache performance: 48% cache HIT

Cache metrics from `bifrost-stage1-ny` after one day:

```
# HELP ipfs_http_blockstore_cache_hit The number of global block cache hits.
# TYPE ipfs_http_blockstore_cache_hit counter
ipfs_http_blockstore_cache_hit 7.273594e+06
# HELP ipfs_http_blockstore_cache_requests The number of global block cache requests.
# TYPE ipfs_http_blockstore_cache_requests counter
ipfs_http_blockstore_cache_requests 1.515003e+07
```

iiuc the above means that  in-memory "frecency" cache of 1024 blocks produces **cache HIT 48% of time**.  
This is not that surprising, every website will cause the same parent blocks to be read multiple times for every subresource on a page.

We run on machines that have 64GiB of memory and `bifrost-gateway` only utilizes  ~5GiB. 

## Proposal: increase cache size

Improving cache hit here won't improve things like video seeking or fetching big files, but will have impact for how fast popular websites and directory enumerations load, avoiding trashing of the most popular content. 

### Tasks 

- [ ]  refactor cache size configuration: remove CLI parameter, and use ENV variable instead (to match plan from #43 and new configuration convention agreed with George) 
- [ ] with ability to tweak cache size with env variable, run experiments on `bifrost-stage1-ny` and  increase block cache size, let's say initiallly  x5 (to 5120 blocks)  and see if it improves cache hit, or if it produces diminishing returns. 
- [ ] Once we find the optimal cache size on staging, update implicit default

**Comment by lidel** [comment]
I've restarted `bifrost-stage1-ny` with  [BLOCK_CACHE_SIZE](https://github.com/ipfs/bifrost-gateway/blob/main/docs/environment-variables.md#block_cache_size) increased from 1024 to 2048.

```
2023/02/24 00:57:10 Starting bifrost-gateway 2023-02-22-c0c8fa3
2023/02/24 00:57:10 Block cache size: 2048
```

Will check Friday EOD  if  cache hit ratio improved.

**Comment by lidel** [comment]
after ~12h:
```
ipfs_http_blockstore_cache_hit 1.0137958e+07
ipfs_http_blockstore_cache_requests 1.9706903e+07
```

hits still at  ~51%, which confirms that we could increase it further to save on more roundtrips.

I am setting it to 4096 now:

```
2023/02/24 13:03:22 Starting bifrost-gateway 2023-02-24-dca4ba9
2023/02/24 13:03:22 Block cache size: 4096
```

**Comment by lidel** [comment]
in 6h 4096 produced "only" 40% hit ratio

```
ipfs_http_blockstore_cache_hit 1.297952e+06
ipfs_http_blockstore_cache_requests 3.199352e+06
```

**Comment by lidel** [comment]
After weekend, the `BLOCK_CACHE_SIZE=4096` result was still around ~41%: 

```
ipfs_http_blockstore_cache_hit 5.595748e+06
ipfs_http_blockstore_cache_requests 1.3580514e+07
```

**Comment by lidel** [comment]
Cache hit % is pretty successful across instances, including staging where we deployed #61 with Graph API enabled:
> ![2023-04-03_23-39](https://user-images.githubusercontent.com/157609/229633538-c9ae8e55-bd9b-4439-9117-460feafb14bc.png)

I am going to double the cache size on staging to `8192` and check if it makes any difference for graph backend.

**Comment by lidel** [comment]
8192 produces similar hit ratio:
> ![Screenshot 2023-04-04 at 21-14-52 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/229897792-c67aae06-015a-439a-bfc7-39a2337ee06d.png)

Memory usage is minimal:
> ![Screenshot 2023-04-04 at 21-21-29 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/229898284-4da54ef3-8f75-4a5d-b690-e99b38e897d2.png)


I've bumped it to 16384.
