### ISSUE TITLE
Support Trace Context HTTP headers

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#68]
Ref.  
- https://github.com/w3c/trace-context#trace-context-specification
- https://w3c.github.io/trace-context/ 
  - https://w3c.github.io/trace-context/#processing-model
- https://github.com/ipfs/kubo/issues/9168 + https://github.com/ipfs/kubo/pull/9180

Quick thoughts:
- Whatever we establish here, others in IPFS Ecosystem will see, and assume this is "standard best practice" – we should plan for long term
- This should be turn-key solution for everyone running boxo/gateway, not just bifrost-gateway  
- bifrost-gateway should ensure tracing info is always present
  -  If it is missing in request, bifrost-gateway would create one. ([spec](https://w3c.github.io/trace-context/#mutating-the-traceparent-field))
  - If it is present in request, we update ids in the chain.
     - For Rhea, we will be creating trace parent on LBs ([slack thread](https://filecoinproject.slack.com/archives/C04JQ9X7ENB/p1679942350966959)), but if there is no load balancer in front of bifrost-gateway, then it should initialize trace chain.

```[tasklist]
### Tasks
- [x] https://github.com/ipfs/bifrost-gateway/pull/74
- [ ]  https://github.com/filecoin-saturn/caboose/pull/87
- [ ] https://github.com/filecoin-saturn/L1-node/issues/337
```

**Comment by lidel** [comment]
wip in https://github.com/ipfs/bifrost-gateway/pull/74#pullrequestreview-1373913705, quick demo:

> I'm using Kubo @ [ipfs/kubo#9801](https://github.com/ipfs/kubo/pull/9801) for testing.
> 
> Connected traces of Bifrost Gateway proxying requests to Kubo (`PROXY_GATEWAY_URL`):
> 
> ![image](https://user-images.githubusercontent.com/5447088/230405022-b4fd6e7f-c37b-43a9-867f-efefdeefe70e.png)
> 
> Connected traces of Bifrost Gateway proxying IPNS records to Kubo (`KUBO_RPC_URL`):
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/5447088/230407212-84f820e0-184a-46d8-ac89-a9ac3db5d621.png">
> 
> `STRN_ORCHESTRATOR_URL` should work since we wrap the caboose transport with `otelhttp` and caboose already uses the request with context:
> 
> https://github.com/filecoin-saturn/caboose/blob/34e6ab0f0e60ed6bef02b06242573aa5ab06bd37/fetcher.go#L215-L219

**Comment by lidel** [comment]
@willscott @aschmahmann fyi support for `traceparent` header landed in https://github.com/ipfs/bifrost-gateway/pull/74.
When [a valid `traceparent` header](https://github.com/ipfs/boxo/blob/main/docs/tracing.md#generate-traceparent-header) is present in request, traces can be inspected via enabled exporters.


For example, `OTEL_TRACES_EXPORTER=jaeger` with [Jaeger UI](https://github.com/ipfs/boxo/blob/main/docs/tracing.md#using-jaeger-ui) looks like this:


>  ![Screenshot 2023-04-12 at 01-02-57 Jaeger UI](https://user-images.githubusercontent.com/157609/231313167-2ce15acc-d54e-4165-b73c-a12fd556dbde.png)


---- 


Reopening as we need to add tracing to caboose and other types fo HTTP requests sent:

- [ ] confirm that `traceparent` is applied to all requests sent by bifrost-gateway to other systems
  - [x] `KUBO_RPC_URL`  → routing.go
  - [x] when `PROXY_GATEWAY_URL`  is set  → blockstore_proxy.go
  - [ ] when `STRN_ORCHESTRATOR_URL` is set → open PR in [caboose](https://github.com/filecoin-saturn/caboose) that ensures header is forwarded to Saturn L1 with every request?

**Comment by hacdias** [comment]
@lidel it should already work. Caboose uses the HTTP Client it is given and we updated it to be wrapped via the `otelhttp.NewTransport` handler:

https://github.com/ipfs/bifrost-gateway/blob/660ec70a8a7e058c235dfa92e1f50eaab4db1966/blockstore_caboose.go#L63-L89

In addition, Caboose is already creating [requests with Context](https://github.com/filecoin-saturn/caboose/blob/65275d010784f61e0dc00abb2a73677f80276447/fetcher.go#L216-L220). Assuming the context is being correctly propagated in the Caboose side, the `traceparent` header should be propagating well. Since caboose is a library and not a standalone service, I don't think we need to make further changes. The Saturn nodes should, however, be wrapped with the `otelhttp.NewHandler` such that they parse the incoming requests Trace Context.

Things that can be done to future improve the tracing (not sure whose responsability is it since it falls outside the `ipfs` org):

- [ ] Caboose could have its own spans.
- [ ] Saturn nodes should use [`otelhttp.NewHandler`](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp#NewHandler), or equivalent on the language of use.
- [ ] Saturn nodes should have their own tracing spans.
- [ ] Saturn nodes should be able to export their tracing data.

Only with all that data we will be able to trace a single requests lifecycle from the browser to the Saturn node(s).

**Comment by lidel** [comment]
Closed, as the remaining work needs to happen in Saturn.
